
package org.donstu.async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FitnessService", targetNamespace = "https://donstu.org/fitness", wsdlLocation = "http://127.0.0.1:8088/fitness?wsdl")
public class FitnessService_Service
    extends Service
{

    private final static URL FITNESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FITNESSSERVICE_EXCEPTION;
    private final static QName FITNESSSERVICE_QNAME = new QName("https://donstu.org/fitness", "FitnessService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8088/fitness?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FITNESSSERVICE_WSDL_LOCATION = url;
        FITNESSSERVICE_EXCEPTION = e;
    }

    public FitnessService_Service() {
        super(__getWsdlLocation(), FITNESSSERVICE_QNAME);
    }

    public FitnessService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FITNESSSERVICE_QNAME, features);
    }

    public FitnessService_Service(URL wsdlLocation) {
        super(wsdlLocation, FITNESSSERVICE_QNAME);
    }

    public FitnessService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FITNESSSERVICE_QNAME, features);
    }

    public FitnessService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FitnessService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FitnessService
     */
    @WebEndpoint(name = "FitnessPort")
    public FitnessService getFitnessPort() {
        return super.getPort(new QName("https://donstu.org/fitness", "FitnessPort"), FitnessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FitnessService
     */
    @WebEndpoint(name = "FitnessPort")
    public FitnessService getFitnessPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://donstu.org/fitness", "FitnessPort"), FitnessService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FITNESSSERVICE_EXCEPTION!= null) {
            throw FITNESSSERVICE_EXCEPTION;
        }
        return FITNESSSERVICE_WSDL_LOCATION;
    }

}
