
package org.donstu.async;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FitnessService", targetNamespace = "https://donstu.org/fitness")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FitnessService {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.donstu.async.GetAvailableZonesResponse>
     */
    @WebMethod(operationName = "getAvailableZones")
    @RequestWrapper(localName = "getAvailableZones", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.async.GetAvailableZones")
    @ResponseWrapper(localName = "getAvailableZonesResponse", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.async.GetAvailableZonesResponse")
    public Response<GetAvailableZonesResponse> getAvailableZonesAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAvailableZones")
    @RequestWrapper(localName = "getAvailableZones", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.async.GetAvailableZones")
    @ResponseWrapper(localName = "getAvailableZonesResponse", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.async.GetAvailableZonesResponse")
    public Future<?> getAvailableZonesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetAvailableZonesResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.async.GymZone>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableZones", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.async.GetAvailableZones")
    @ResponseWrapper(localName = "getAvailableZonesResponse", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.async.GetAvailableZonesResponse")
    @Action(input = "https://donstu.org/fitness/FitnessService/getAvailableZonesRequest", output = "https://donstu.org/fitness/FitnessService/getAvailableZonesResponse")
    public List<GymZone> getAvailableZones();

}
