
package org.donstu.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FitnessService", targetNamespace = "https://donstu.org/fitness")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FitnessService {


    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.client.GymZone>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableZones", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.client.GetAvailableZones")
    @ResponseWrapper(localName = "getAvailableZonesResponse", targetNamespace = "https://donstu.org/fitness", className = "org.donstu.client.GetAvailableZonesResponse")
    @Action(input = "https://donstu.org/fitness/FitnessService/getAvailableZonesRequest", output = "https://donstu.org/fitness/FitnessService/getAvailableZonesResponse")
    public List<GymZone> getAvailableZones();

}
